In [3]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/vibhorchander/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/vibhorchander/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-macosx_11_0_arm64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 35.3 MB/s  0:00:00eta 0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.6

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Pandas is a powerful library used for data analysis and manipulation.
# We import it so we can create DataFrames and work with tabular data.
import pandas as pd

In [ ]:
# Pandas offers a 2-D, mutable-size, heterogeneous table data structure.
# This is called a DataFrame, which stores rows and columns of data.
x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

df = pd.DataFrame(x)

df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [ ]:
# Selecting a single column from a DataFrame creates a new DataFrame.
x = df[['ID']]
x

   ID
0   1
1   2
2   3
3   4

In [ ]:
# Select multiple columns by listing their names inside a list.
z = df[['ID', 'Salary', 'Department']]
z

   ID  Salary       Department
0   1  100000  Architect Group
1   2   80000   Software Group
2   3   50000      Design Team
3   4   60000   Infrastructure

In [ ]:
# A dictionary can be converted into a DataFrame for tabular data analysis.
student_dict = {'Student':['David','Samuel','Terry','Evan'],'Age':[27,24,22,32], 'Country':['UK','Canada','China','USA'], 'Course':['Python','DS','ML','Web Dev'], 'Marks': [85,72,89,76]}
std_df = pd.DataFrame(student_dict)
std_df

  Student  Age Country   Course  Marks
0   David   27      UK   Python     85
1  Samuel   24  Canada       DS     72
2   Terry   22   China       ML     89
3    Evan   32     USA  Web Dev     76

In [ ]:
# Selecting one column keeps the result as a DataFrame when using double brackets.
marks = std_df[['Marks']]
marks

   Marks
0     85
1     72
2     89
3     76

In [ ]:
# We can also choose multiple columns to view a smaller table.
c = std_df[['Country','Course']]
c

  Country   Course
0      UK   Python
1  Canada       DS
2   China       ML
3     USA  Web Dev

In [ ]:
# A Series is a one-dimensional labeled array in Pandas.
# It behaves like a single column with an index.
x = std_df['Student']
x

0     David
1    Samuel
2     Terry
3      Evan
Name: Student, dtype: str

In [ ]:
# The type() function confirms that a Series is not a DataFrame.
type(x)

pandas.Series

In [ ]:
# .iloc[] selects a value by integer row and column position.
std_df.iloc[0,0]

'David'

In [ ]:
# .loc[] selects a value by row label and column label.
std_df.loc[0,'Marks']

np.int64(85)

In [ ]:
# This keeps a copy of the DataFrame for further analysis.
std_df_1 = std_df
# std_df_1 = std_df_1.set_index("Index")

In [ ]:
# .head() shows the first few rows of the DataFrame.
std_df_1.head()

  Student  Age Country   Course  Marks
0   David   27      UK   Python     85
1  Samuel   24  Canada       DS     72
2   Terry   22   China       ML     89
3    Evan   32     USA  Web Dev     76

In [ ]:
# Access the value in a specific row and column using labels.
std_df_1.loc[0,'Age']

np.int64(27)

In [ ]:
# This fetches a value using row and column positions, not labels.
std_df_1.iloc[1,4]

np.int64(72)

In [ ]:
# Slice rows and columns to view a subset of the DataFrame.
std_df.iloc[0:2,0:3]

  Student  Age Country
0   David   27      UK
1  Samuel   24  Canada

In [ ]:
# Using .loc with a range of rows and selected columns helps filter data by labels.
std_df.loc[0:2,'Student': 'Marks']

  Student  Age Country  Course  Marks
0   David   27      UK  Python     85
1  Samuel   24  Canada      DS     72
2   Terry   22   China      ML     89

In [51]:
%pip install xlrd

%pip install openpyxl 
try:
    import piplite
    await piplite.install(['xlrd', 'openpyxl'])
except ModuleNotFoundError:
    %pip install xlrd openpyxl
try:
    await piplite.install(['xlrd', 'openpyxl'])
except (ImportError, NameError):
    %pip install xlrd openpyxl

Requirement already satisfied: xlrd in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.0.2)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: xlrd in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.0.2)
Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: xlrd in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.0.2)
Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Read a CSV file into a DataFrame so we can analyze the data.
df = pd.read_csv("TopSellingAlbumd.csv")

In [ ]:
# Show the first few rows of the CSV data.
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0

In [ ]:
# Select a value by row label and column name from the CSV DataFrame.
df.loc[0,'Artist']

'Michael Jackson'

In [ ]:
# Select the first row and first column by integer position.
df.iloc[0,0]

'Michael Jackson'